<?php
// $Id: panels_page.module,v 1.1.2.7 2007/09/17 19:11:49 merlinofchaos Exp $

/**
 * Implementation of hook_help()
 */
function panels_page_help($section = '') {
  switch ($section) {
    case 'admin/panels/panel-page':
    case 'admin/panels/panel-page/list':
      return t('<p>You may peruse a list of your current panels layouts and edit them, or click add to create a new page.</p>');
    case 'admin/panels/panel-page/add':
      return t('<p>Choose a layout for your new page from the list below.</p>');
  }
}

/**
 * Implementation of hook_perm()
 */
function panels_page_perm() {
  return array('create panel-pages', 'access all panel-pages');
}

/**
 * Implementation of hook_menu()
 */
function panels_page_menu($may_cache) {
  $items = array();
  $panels = panels_page_load_all();
  if ($may_cache) {
    $access = user_access('create panel-pages');
    $items[] = array(
      'path' => 'admin/panels/panel-page',
      'title' => t('Panel pages'),
      'access' => $access,    
      'callback' => 'panels_page_passthru',
      'callback arguments' => array('panels_page_list_page'),
      'description' => t('Create and administer panel-pages (complex layout pages with URLs).'),
    );
    $items[] = array(
      'path' => 'admin/panels/panel-page/list',
      'title' => t('List'),
      'access' => $access,    
      'callback' => 'panels_page_passthru',
      'callback arguments' => array('panels_page_list_page'),
      'weight' => -10,
      'type' => MENU_DEFAULT_LOCAL_TASK,
    );
    $items[] = array(
      'path' => 'admin/panels/panel-page/add',
      'title' => t('Add'),
      'access' => $access,    
      'callback' => 'panels_page_passthru',
      'callback arguments' => array('panels_page_add_page'),
      'type' => MENU_LOCAL_TASK,
    );
    $items[] = array(
      'path' => 'admin/panels/panel-page/import',
      'title' => t('Import'),
      'access' => $access,    
      'callback' => 'panels_page_passthru',
      'callback arguments' => array('panels_page_import_page'),
      'type' => MENU_LOCAL_TASK,
    );
    $items[] = array(
      'path' => 'admin/panels/panel-page/settings',
      'title' => t('Settings'),
      'access' => $access,    
      'callback' => 'panels_page_settings',
      'weight' => 5,
      'type' => MENU_LOCAL_TASK,
    );
    $items[] = array(
      'path' => 'admin/panels/panel-page/add/layout',
      'title' => t('Add'),
      'access' => $access,    
      'callback' => 'panels_page_passthru',
      'callback arguments' => array('panels_page_add_layout_page'),
      'type' => MENU_LOCAL_TASK,
    );
    $items[] = array(
      'path' => 'admin/panels/panel-page/disable',
      'access' => $access,    
      'callback' => 'panels_page_passthru',
      'callback arguments' => array('panels_page_disable_page'),
      'weight' => -1,
      'type' => MENU_CALLBACK,
    );
    $items[] = array(
      'path' => 'admin/panels/panel-page/enable',
      'access' => $access,    
      'callback' => 'panels_page_passthru',
      'callback arguments' => array('panels_page_enable_page'),
      'weight' => -1,
      'type' => MENU_CALLBACK,
    );

    // Ajax responder
    $items[] = array(
      'path' => 'panels/argument/ajax/add',
      'access' => $access,    
      'callback' => 'panels_page_passthru',
      'callback arguments' => array('panels_page_ajax_argument_add'),
      'type' => MENU_CALLBACK,
    );
    $items[] = array(
      'path' => 'panels/argument/ajax/edit',
      'access' => $access,    
      'callback' => 'panels_page_passthru',
      'callback arguments' => array('panels_page_ajax_argument_edit'),
      'type' => MENU_CALLBACK,
    );

    // Get all panels and, if enabled, create menu items.
    foreach ($panels as $panel_page) {
      if (empty($panel_page->disabled)) {
        // Only create menu items based on the path if it's not a variable path.
        if (strpos($panel_page->path, '%') === FALSE) {
          panels_page_menu_items($items, $panel_page->path, $panel_page, FALSE, array($panel_page->name));  
        }
        panels_page_menu_items($items, 'admin/panels/panel-page/' . $panel_page->name, $panel_page, TRUE, array($panel_page->name));
      }
    }
  }
  else {
    // Look for panels with variable arguments.
    // Build an array of $urls because 'real' URLs will take precedence over
    // argument filled URLs
    $urls = array();
    foreach ($panels as $panel_page) {
      $url[$panel_page->path] = TRUE;
    }

    foreach ($panels as $panel_page) {
      if (strpos($panel_page->path, '%') !== FALSE) {
        $path = explode('/', $panel_page->path);
        $match = TRUE;
        foreach ($path as $id => $chunk) {
          if ($chunk != '%' && $chunk != arg($id)) {
            $match = FALSE;
            break;
          }
        }
        // It's a MATCH! Construct the URL
        if ($match) {
          $args = array($panel_page);
          reset($panel_page->arguments);
          $count = 0;
          foreach ($path as $id => $chunk) {
            if ($chunk != '%') {
              continue;
            }
            // For arguments that are embedded in the URL, we require the
            // argument handler to return a context, if there is an argument handler.
            $argument = current($panel_page->arguments);
            if ($argument) {
              $context = panels_argument_get_context(
                $argument['name'], arg($id), $argument['argument_settings'], NULL, $count);
              if (!$context) {
                break;
              }
              $panel_page->context[$count] = $context;
              $count++;                
            }
            $path[$id] = arg($id);
            $args[] = arg($id);
            next($panel_page->arguments);
          }
          panels_page_menu_items($items, implode('/', $path), $panel_page, FALSE, $args);  
        }
      }
    }
  }
  return $items;
}

/**
 * Helper function to add a menu item for a panel.
 */
function panels_page_menu_items(&$items, $base, $page, $basic = FALSE, $args = array()) {
  $view_access = panels_page_access($page);
  $access = user_access('create panel-pages');

  if ($basic) {
    $items[] = array(
      'path' => $base,
      'title' => t('View'),
      'access' => $view_access,    
      'callback' => 'panels_page_view_page',
      'callback arguments' => $args,
      'weight' => -10,
      'type' => MENU_CALLBACK,
    );
  }
  else {
    _panels_page_create_menu_item($items, $page, $base, $view_access, $args);
  }

  $items[] = array(
    'path' => $base . '/view',
    'title' => t('View'),
    'access' => $view_access,    
    'callback' => 'panels_page_view_page',
    'callback arguments' => $args,
    'weight' => -10,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
/*
  $items[] = array(
    'path' => $base . '/edit',
    'title' => t('Edit'),
    'access' => $access,    
    'callback' => 'panels_page_passthru',
    'callback arguments' => array('panels_page_edit', $page->name),
    'weight' => -5,
    'type' => MENU_LOCAL_TASK,
  );
*/
  $items[] = array(
    'path' => $base . '/edit/general',
    'title' => t('Settings'),
    'access' => $access,    
    'callback' => 'panels_page_passthru',
    'callback arguments' => array('panels_page_edit', $page->name),
    'weight' => -5,
    'type' => MENU_LOCAL_TASK,
  );
  $items[] = array(
    'path' => $base . '/edit/advanced',
    'title' => t('Advanced'),
    'access' => $access,    
    'callback' => 'panels_page_passthru',
    'callback arguments' => array('panels_page_edit_advanced', $page->name),
    'weight' => -4,
    'type' => MENU_LOCAL_TASK,
  );

  // Set up for the 'default' display.
  $items[] = array(
    'path' => $base . '/edit/layout',
    'title' => t('Layout'),
    'access' => $access,    
    'callback' => 'panels_page_passthru',
    'callback arguments' => array('panels_page_edit_layout', $page->name),
    'weight' => -3,
    'type' => MENU_LOCAL_TASK,
  );

  $items[] = array(
    'path' => $base . '/edit/settings',
    'title' => t('Layout settings'),
    'access' => $access,    
    'callback' => 'panels_page_passthru',
    'callback arguments' => array('panels_page_edit_layout_settings', $page->name, NULL),
    'weight' => -3,
    'type' => MENU_LOCAL_TASK,
  );

  $items[] = array(
    'path' => $base . '/edit/content',
    'title' => t('Content'),
    'access' => $access,    
    'callback' => 'panels_page_passthru',
    'callback arguments' => array('panels_page_edit_content', $page->name),
    'weight' => -1,
    'type' => MENU_LOCAL_TASK,
  );

  $items[] = array(
    'path' => $base . '/edit/layout/default',
    'title' => t('Default'),
    'access' => $access,    
    'callback' => 'panels_page_passthru',
    'callback arguments' => array('panels_page_edit_layout', $page->name),
    'weight' => -3,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  $items[] = array(
    'path' => $base . '/edit/settings/default',
    'title' => t('Default'),
    'access' => $access,    
    'callback' => 'panels_page_passthru',
    'callback arguments' => array('panels_page_edit_layout_settings', $page->name, NULL),
    'weight' => -3,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  $items[] = array(
    'path' => $base . '/edit/content/default',
    'title' => t('Default'),
    'access' => $access,    
    'callback' => 'panels_page_passthru',
    'callback arguments' => array('panels_page_edit_content', $page->name),
    'weight' => -1,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  if (!empty($page->displays)) {
    foreach ($page->displays as $display_id => $info) {
      $items[] = array(
        'path' => $base . '/edit/layout/' . $display_id,
        'title' => $info['title'],
        'access' => $access,    
        'callback' => 'panels_page_passthru',
        'callback arguments' => array('panels_page_edit_layout', $page->name, $display_id),
        'weight' => -3,
        'type' => MENU_LOCAL_TASK,
      );

      $items[] = array(
        'path' => $base . '/edit/settings/' . $display_id,
        'title' => $info['title'],
        'access' => $access,    
        'callback' => 'panels_page_passthru',
        'callback arguments' => array('panels_page_edit_layout_settings', $page->name, $display_id),
        'weight' => -3,
        'type' => MENU_LOCAL_TASK,
      );

      $items[] = array(
        'path' => $base . '/edit/content/' . $display_id,
        'title' => $info['title'],
        'access' => $access,    
        'callback' => 'panels_page_passthru',
        'callback arguments' => array('panels_page_edit_content', $page->name, $display_id),
        'weight' => -1,
        'type' => MENU_LOCAL_TASK,
      );
    }
  }

  $items[] = array(
    'path' => $base . '/export',
    'title' => t('Export'),
    'access' => $access,    
    'callback' => 'panels_page_passthru',
    'callback arguments' => array('drupal_get_form', 'panels_page_edit_export', $page->name),
    'weight' => -9,
    'type' => MENU_LOCAL_TASK,
  );
  $items[] = array(
    'path' => $base . '/delete',
    'title' => t('Delete panel page'),
    'access' => $access,    
    'callback' => 'panels_page_passthru',
    'callback arguments' => array('drupal_get_form', 'panels_page_delete_confirm', $page->name),
    'type' => MENU_CALLBACK,
  );
}

/**
 * Create a menu item for a panel page.
 */
function _panels_page_create_menu_item(&$items, $panel_page, $path, $access, $args = array()) {
  $title = filter_xss_admin(panels_page_get_title($panel_page, 'menu'));
  $type = _panels_page_menu_type($panel_page);
  if ($type == MENU_LOCAL_TASK || $type == MENU_DEFAULT_LOCAL_TASK) {
    $weight = $panel_page->menu_tab_weight;
  }
  $items[] = _panels_page_menu_item($path, $title, $panel_page, $args, $access, $type, $weight);

  if ($type == MENU_DEFAULT_LOCAL_TASK && dirname($path) && dirname($path) != '.') {
    switch ($panel_page->menu_tab_default_parent_type) {
      case 'tab':
        $parent_type = MENU_LOCAL_TASK;
        break;
      case 'normal':
        $parent_type = MENU_NORMAL_ITEM;
        break;
      default:
      case 'existing':
        $parent_type = 0;
        break;
    }
    if ($parent_type) {
      $title = filter_xss_admin(panels_page_get_title($panel_page, 'menu-parent'));
      $weight = $panel_page->menu_parent_tab_weight;
      $items[] = _panels_page_menu_item(dirname($path), $title, $panel_page, $args, $access, $parent_type, $weight);
    }
  }
}

/**
 * Helper function to create a menu item for a panel.
 */
function _panels_page_menu_item($path, $title, $panel_page, $args, $access, $type, $weight = NULL) {
  $retval = array('path' => $path,
    'title' => $title,
    'callback' => 'panels_page_view_page',
    'callback arguments' => $args,
    'access' => user_access('access content') && $access,
    'type' => $type,
  );
  if ($weight !== NULL) {
    $retval['weight'] = $weight;
  }
  return $retval;
}

/**
 * Determine what menu type a panel needs to use.
 */
function _panels_page_menu_type($panel_page) {
  if ($panel_page->menu) {
    if ($panel_page->menu_tab_default) {
      $type = MENU_DEFAULT_LOCAL_TASK;
    }
    else if ($panel_page->menu_tab) {
      $type = MENU_LOCAL_TASK;
    }
    else {
      $type = MENU_NORMAL_ITEM;
    }
  }
  else {
    $type = MENU_CALLBACK;
  }
  return $type;
}

/**
 * Determine if the specified user has access to a panel.
 */
function panels_page_access($panel_page, $account = NULL) {
  if (!$account) {
    global $user;
    $account = $user;
  }

  // Administrator privileges
  if (user_access('access all panel-pages', $account)) {
    return TRUE;
  }

  // All views with an empty access setting are available to all roles.
  if (!$panel_page->access || !is_array($panel_page->access)) { 
    return TRUE;
  }

  // Otherwise, check roles
  static $roles = array();
  if (!isset($roles[$account->uid])) {
    $roles[$account->uid] = array_keys($account->roles);
    $roles[$account->uid][] = $account->uid ? DRUPAL_AUTHENTICATED_RID : DRUPAL_ANONYMOUS_RID;
  }

  return array_intersect($panel_page->access, $roles[$account->uid]);
}


/**
 * Get the title for a panel page, given a context.
 */
function panels_page_get_title($panel_page, $context = 'page', $default_title = NULL) {
  if ($context == 'menu-parent' && $panel_page->menu_parent_title) {
    return $panel_page->menu_parent_title;
  }

  if (in_array($context, array('menu', 'menu-parent')) && $panel_page->menu_title) {
    return $panel_page->menu_title;
  }
  
  if ($panel_page->context) {
    $substitutions = array();
    $title = NULL;
    $count = 1;
    foreach ($panel_page->context as $id => $context) {
      $substitutions['%' . ($count++)] = panels_argument_get_title($panel_page->arguments[$id]['name'], $context);
      if (!empty($panel_page->arguments[$id]['title'])) {
        $title = $panel_page->arguments[$id]['title'];
      }
    }

    if ($title) {
      if ($substitutions) {
        $title = strtr($title, $substitutions);
      }

      return $title;
    }
  }

  if ($panel_page->title) {
    return $panel_page->title;
  }

  if (is_null($default_title)) {
    return t('No title');
  }
  else {
    return $default_title;
  }
}

/**
 * Figure out if a panel is the current page; mostly useful in theming.
 */
function panels_page_get_current($page = NULL) {
  static $cache = NULL;
  if (isset($page)) {
    $cache = $page;
  }

  return $cache;
}

// ---------------------------------------------------------------------------
// panel page administrative pages

/**
 * Settings for panel pages
 */
function panels_page_settings() {
  require_once drupal_get_path('module', 'panels') . '/includes/common.inc';
  return drupal_get_form('panels_common_settings', 'panels_page');
}

/**
 * Pass-through to admin.inc
 */
function panels_page_passthru() {
  $args = func_get_args();
  $callback = array_shift($args);

  include_once './' . panels_get_path('panels_page/panels_page.admin.inc');
  return call_user_func_array($callback, $args);
}

// ---------------------------------------------------------------------------
// view panels page

/**
 * Page callback to view a panel page.
 */
function panels_page_view_page($panel_page) {
  if (!is_object($panel_page)) {
    $panel_page = panels_page_load($panel_page);
  }
  if (!$panel_page) {
    return drupal_not_found();
  }
  
  $args = func_get_args();
  array_shift($args); // remove the name.

  if (empty($panel_page->context)) {
    $panel_page->context = array();
  }

  $form = NULL;
  if ($panel_page->arguments) {
    $count = 0;
    foreach ($panel_page->arguments as $i => $argument) {
      $context = panels_argument_get_context($argument['name'], $args[$count], $argument['argument_settings'], $args, $count);
      $count++;
      if (!empty($context)) {
        $panel_page->context[$i] = $context;
        $d = panels_argument_choose_display($argument['name'], $argument['argument_settings'], $context);
        if ($d) {
          $display_candidate = "argument_$i" . '-' . $d;
        }
        if (isset($context->form_id)) {
          $form = $context;
        }
      }
      else if ($argument['default'] == '404') {
        return drupal_not_found();
      }
    }
  }

  // Figure out which display to use.
  if (isset($display_candidate)) {
    $display = panels_page_fetch_display($panel_page, $display_candidate);
  }
  else {
    $display = panels_load_display($panel_page->did);
  }

  // This is the first point at which it is safe to add items to the display
  // as the argument handling, above, may choose which display is actually
  // used.
  $display->args = $args;
  $display->context = $panel_page->context;
  $display->css_id = $panel_page->css_id;

  // Set this as 'current' so that other stuff can utilize it.
  panels_page_get_current($panel_page);

  if ($form) {
    $form->data['#theme'] = 'panels_page_render_form';
    $form->data['#display'] = $display;
    $output = drupal_render_form($form->form_id, $form->data);
  }
  else {
    $output = panels_render_display($display);
  }

  // set title afterward to ensure title is retained.
  if ($output == NULL) {
    watchdog('panels', t('Unable to find requested layout %s', array('%s' => check_plain($display->layout))));
    return drupal_not_found();
  }

  drupal_set_title(filter_xss_admin(panels_page_get_title($panel_page, 'page', '')));

  if ($panel_page->css) {
    drupal_set_html_head("<style type=\"text/css\" media=\"all\">" . filter_xss_admin($panel_page->css) . "</style>\n");
  }
  if ($panel_page->no_blocks) {
    print theme('page', $output, FALSE);
  }
  else {
    return $output;
  }
}

/**
 * Theme function to render our panel as a form. We need to do this so that
 * the entire display is inside the form.
 */
function theme_panels_page_render_form($form) {
  $form['#children'] = panels_render_display($form['#display']);
  return theme('form', $form);
}

/**
 * Load a display based upon information from the $displays list.
 */
function panels_page_fetch_display($panel_page, $id) {
  $info = $panel_page->displays[$id];

  // If the 'display' is set it's the result of an export/default
  if (isset($info['display'])) {
    return $info['display'];
  }

  if (is_numeric($info['did'])) {
    return panels_load_display($info['did']);
  }

  // At this point the display does not yet exist, which means we need to
  // create one and save the panel page to reflect this.

  // Arguments can provide their own default to use as a template
  if (!empty($info['default']) && is_numeric($panel_page->displays[$info['default']]['did'])) {
    $original = panels_load_display($panel_page->displays[$info['default']]['did']);
  }

  if (!isset($original)) {
    if (empty($panel_page->display)) {
      $original = panels_load_display($panel_page->did);
    }
    else {
      $original = $panel_page->display;
    }
  }

  // Make a copy of the display; using the export forces all the IDs properly.  
  $code = panels_export_display($original);
  $original = eval($code);

  panels_save_display($display);
  $panel_page->displays[$id]['did'] = $display->did;

  // TODO: Having to clone this sucks.
  panels_page_save(drupal_clone($panel_page));
  return $display;
}

// ---------------------------------------------------------------------------
// Database functions

/**
 * Fetch all panel pages in the system. This function does not cache.
 */
function panels_page_load_all( $page_size = 0) {
  $pages = $dids = array();
  $query = "SELECT * FROM {panels_page}";
  if ($page_size) {
    $result = pager_query($query, $page_size);
  }
  else {
    $result = db_query($query);
  }

  while ($page = db_fetch_object($result)) {
    $page->access = ($page->access ? explode(', ', $page->access) : array());
    $page->arguments = (!empty($page->arguments)) ? unserialize($page->arguments) : array();
    $page->displays = (!empty($page->displays)) ? unserialize($page->displays) : array();
    $page->contexts = (!empty($page->contexts)) ? unserialize($page->contexts) : array();
    $page->type = t('Local');
    $pages[$page->name] = $page;
  }

  $status = variable_get('panel_page_defaults', array());
  foreach (panels_page_default_panels() as $page) {
    // Determine if default panel is enabled or disabled.
    if (isset($status[$page->name])) {
      $page->disabled = $status[$page->name];
    }

    if (!empty($pages[$page->name])) {
      $pages[$page->name]->type = t('Overridden');
    }
    else {
      $page->type = t('Default');
      $pages[$page->name] = $page;
    }
  }
  return $pages;
}

/**
 * Load a panel page and its associated display
 */
function panels_page_load($pid, $load_display = FALSE) {
  static $cache = array();
  if (!array_key_exists($pid, $cache)) {
    if (!is_numeric($pid)) {
      $where = "name = '%s'";
    }
    else {
      $where = 'pid = %d';
    }
    $cache[$pid] = db_fetch_object(db_query("SELECT * FROM {panels_page} WHERE $where", $pid));
    if (!$cache[$pid]) {
      $defaults = panels_page_default_panels();
      if (isset($defaults[$pid])) {
        $cache[$pid] = $defaults[$pid];
        return $cache[$pid];
      }
      return;
    }

    $cache[$pid]->access = ($cache[$pid]->access ? explode(', ', $cache[$pid]->access) : array());
    $cache[$pid]->arguments = (!empty($cache[$pid]->arguments)) ? unserialize($cache[$pid]->arguments) : array();
    $cache[$pid]->displays = (!empty($cache[$pid]->displays)) ? unserialize($cache[$pid]->displays) : array();
    $cache[$pid]->contexts = (!empty($cache[$pid]->contexts)) ? unserialize($cache[$pid]->contexts) : array();

    if ($load_display) {
      $cache[$pid]->display = panels_load_display($cache[$pid]->did);
    }
  }
  return $cache[$pid];
}

/**
 * A list of the fields used in the panel_page table.
 */
function panels_page_fields() {
  return array(
    "name" => "'%s'",
    "title" => "'%s'",
    "arguments" => "'%s'",
    "displays" => "'%s'",
    "contexts" => "'%s'",
    "access" => "'%s'",
    "path" => "'%s'",
    "css_id" => "'%s'",
    "css" => "'%s'",
    "no_blocks" => "%d",
    "menu" => "%d",
    "menu_tab" => "%d",
    "menu_tab_weight" => "%d",
    "menu_title" => "'%s'",
    "menu_tab_default" => "%d",
    "menu_tab_default_parent_type" => "'%s'",
    "menu_parent_title" => "'%s'",
    "menu_parent_tab_weight" => "%d",
  );
}

/**
 * Sanitize a panel prior to saving it.
 */
function panels_page_sanitize($page) {
  foreach (array('arguments', 'displays', 'contexts') as $id) {
    if (empty($page->$id)) {
      $page->$id = array();
    }
  }

  return $page;
}


/**
 * Save a panel page. 
 */
function panels_page_save($panel_page) {
  // Save the display if one was given to us.
  if (!empty($panel_page->display)) {
    $display = panels_save_display($panel_page->display);
  }
  // Ensure empty values get translated correctly. Also make sure we don't
  // mess up the original.
  $page = drupal_clone(panels_page_sanitize($panel_page));

  // serialize the access string.
  $page->access = $page->access ? implode(', ', $page->access) : '';

  $page->arguments = serialize($page->arguments);
  $page->displays = serialize($page->displays);
  $page->contexts = serialize($page->contexts);

  // Create strings for our query from the list of fields.
  $fields = panels_page_fields();
  foreach ($fields as $field => $value) {
    if (isset($page->$field)) {
      $f[] = $field;
      $q[] = $value;
      $v[] = $page->$field;
    }
  }

  if ($page->pid && $page->pid != 'new') {
    if (empty($page->name)) {
      $page->name = 'panel_page_' . $page->pid;
    }
    $query = '';
    foreach ($f as $id => $field) {
      if ($query) {
        $query .= ', ';
      }
      $query .= "$f[$id] = " . $q[$id];
    }

    $v[] = $page->pid;
    db_query("UPDATE {panels_page} SET $query WHERE pid = %d", $v);
  }
  else {
    $page->pid = db_next_id("{panels_page}_pid");
    // Tack our pid and did onto the query. These aren't listed as 'fields' because
    // they can't be updated; once set they are permanent.
    $v[] = $page->pid;
    $v[] = $display->did;

    if (empty($page->name)) {
      $page->name = 'panel_page_' . $page->pid;
    }
    // Yes, this is kind of long but it's a lot easier to match up values.
    db_query("INSERT INTO {panels_page} ( " . implode(', ', $f) . ", pid, did) VALUES (" . implode(', ', $q) . ", %d, %d)", $v);
  }

  menu_rebuild();
  return $page->pid;
}

/**
 * Delete a panel page and its associated display.
 */
function panels_page_delete($panel_page) {
  db_query("DELETE FROM {panels_page} WHERE pid = %d", $panel_page->pid);
  menu_rebuild();
  return panels_delete_display($panel_page->did);
}

/**
 * Export a panel page into PHP code for use in import. The code returned from
 * can be used directly in panels_page_save().
 */
function panels_page_export($panel_page) {
  $output = '';
  $fields = panels_page_fields();
  $output .= '$page = new stdClass()' . ";\n";
  $output .= '$page->pid = \'new\'' . ";\n";
  foreach ($fields as $field => $q) {
    $output .= '  $page->' . $field . ' = ' . var_export($panel_page->$field, TRUE) . ";\n";  
  }
  $output .= panels_export_display($panel_page->display);
  $output .= '$page->display = $display' . ";\n";

  return $output;
}

/**
 * Get all 'default' panels.
 */
function panels_page_default_panels() {
  $panels = module_invoke_all('default_panel_pages');
  if (!is_array($panels)) {
    $panels = array();
  }

  return $panels;
}

